name: Deploy Cloud KMS infra Sample Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened]

env:
  # sample variable
  PROJECT_ID: project1-369205

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.APPLICATION_DEFAULT_CREDENTIALS }}'
      - name: Init
        run: (terraform init)
      - name: Plan
        run: |
          terraform plan
      - name: Deploy Infrastructure
        id: deploy
        run: |
          terraform apply
  destroy:
    if: ${{ vars.DESTROY == 'true' }}
    needs: deploy
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.APPLICATION_DEFAULT_CREDENTIALS }}'
      - name: Destroy Infrastructure
        id: destroy
        run: |
          terraform init
          terraform destroy -auto-approve
