name: Deploy Cloud KMS infra Sample Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened]

env:
  PROJECT_ID: aroonav-demos

jobs:
  terraform-init:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project-alpha/infra-test
    container:
      image: hashicorp/terraform:1.3.3
      volumes:
        - /data
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.APPLICATION_DEFAULT_CREDENTIALS }}'
      - name: Init
        run: (terraform init)
      - name: Plan
        run: |
          terraform plan -out /data/demo.tfplan
      - name: Deploy Infrastructure
        id: deploy
        run: |
          terraform apply /data/demo.tfplan
 destroy:
 - name: Destroy Infrastructure
        id: destroy
        run: |
          terraform init
          terraform destroy -auto-approve
